name: backend

on:
  push:
    branches: [ "master", "main", "implement_workflow" ]
  pull_request:
    branches: [ "master", "main", "implement_workflow" ]

jobs:
  backend_build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: [ 1.21.x ]
        architecture: [x64, x86]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: make isolated_backend_build