name: deploy

on:
  push:
    branches: [ "master", "main", "implement_workflow" ]
  pull_request:
    branches: [ "master", "main", "implement_workflow" ]

jobs:
  backend_build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [ 1.21.x ]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Display Go version
      run: make isolated_backend_build
            
  frontend_build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v3

    - name: Node:${{ matrix.node-version }}, OS:${{ matrix.os }}, arch:${{ matrix.architecture }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: make isolated_frontend_build

  deployment:
    needs: [backend_build, frontend_build]
    runs-on: ubuntu-latest

    steps:
      - name: Push to cannary branch
        uses: actions/checkout@v3

      - name: Configure Email
        run:  git config --local user.email auto.bench@script.yml

      - name: Configure Name
        run:  git config --local user.name bench.yml

      - name: Git Status
        run: git status

      - 