name: frontend

on:
  push:
    branches: [ "master", "main", "implement_workflow" ]
  pull_request:
    branches: [ "master", "main", "implement_workflow" ]

jobs:
  frontend_build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x]
        architecture: [x64, x86]

    steps:
    - uses: actions/checkout@v4

    - name: Node:${{ matrix.node-version }}, OS:${{ matrix.os }}, arch:${{ matrix.architecture }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: make isolated_frontend_build